# .streamlit/secrets.toml

[mongo]
uri = "mongodb+srv://brunorodrigo:123Putao@cluster0.lrr3cgd.mongodb.net/saridulces?retryWrites=true&w=majority&readPreference=primaryPreferred"

# Você pode adicionar outras secrets aqui se precisar
# Exemplo:
# [api_keys]
# Maps = "SUA_CHAVE_API_AQUI"